# Generated by Django 2.2.17 on 2021-01-26 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 19, 56, 4, 568882)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Дорослий', 'Normal'), ('Дитячий', 'Kids'), ('Пенсійний', 'Retiree')], default='Normal', max_length=10),
        ),
    ]
