# Generated by Django 2.2.17 on 2021-01-26 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0004_auto_20210126_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='DaysOfDeparture',
            field=models.CharField(choices=[('Крім неділі', 'Крім неділі'), ('По буднях', 'По буднях')], default='Крім неділі', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 20, 59, 0, 418258)),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureDate', models.DateField()),
                ('status', models.CharField(default='', max_length=20)),
                ('journey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin-panel.Journey')),
            ],
        ),
    ]
